---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Makes sure that the repo cache is fresh
- name: Update APT cache.
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Install python-pip
  include_tasks: setup-python-pip.yml

- name: Install the Docker repository
  include_tasks: "repo-{{ ansible_os_family }}.yml"
  when: not skip_repo

- name: Install Ansible Docker dependencies
  package:
    name: "{{ ansible_dependencies }}"
    state: present
  when: not skip_containerd or not skip_engine

- name: Install Docker dependencies.
  package:
    name: "{{ docker_dependencies }}"
    state: present
  when: not skip_containerd or not skip_engine

- name: Install containerd
  include_tasks: setup-containerd.yml
  when: not skip_containerd

- name: Install the Docker Engine
  include_tasks: setup-docker-engine.yml
  when: not skip_engine

- name: Install the Docker CLI
  include_tasks: setup-docker-cli.yml
  when: not skip_cli

- block:
  - name: Setup the Docker Swarm Cluster
    include_tasks: setup-swarm-cluster.yml
  - name: Secure Swarm cluster
    include_tasks: secure-swarm-cluster.yml
    when: not skip_secure_swarm
  when: not skip_swarm

- name: Add Docker admin users to the Docker group
  include_tasks: setup-docker-group.yml
  when: not skip_group

- name: Install docker-py
  include_tasks: setup-docker-py.yml
  when: not skip_docker_py

- name: Install docker-compose
  include_tasks: setup-docker-compose.yml
  when: not skip_docker_compose
