---
- block:
  - name: Add the Docker buildx Zypper repository.
    community.general.zypper_repository:
      repo: "{{ docker_buildx_repo }}"
      state: present
      auto_import_keys: yes
      overwrite_multiple: yes
      runrefresh: yes
  - name: Add the Leap Zypper repository for docker-py.
    community.general.zypper_repository:
      repo: "{{ docker_python_repo }}"
      name: leap_oss
      state: present
      auto_import_keys: yes
      overwrite_multiple: yes
      runrefresh: yes
  when: ansible_distribution.startswith('openSUSE Leap Micro')
