---

- block:

    - name: Prefix the Docker package version with the correct separator on RedHat.
      set_fact:
        _docker_package_version: "-{{ docker_package_version }}"
      when: ansible_os_family == 'RedHat'

    - name: Prefix the Docker package version with the correct separator on Debian.
      set_fact:
        _docker_package_version: "={{ docker_package_version }}"
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Suse'

  when: docker_package_version | length > 0

- name: Install Docker.
  package:
    name: "{{ docker_package_name }}{{ _docker_package_version | default('') }}"
    state: "{{ docker_package_state }}"
  register: result
  failed_when:
    - result.stdout is defined
    - '"Problem occurred during or after installation or removal of packages" in result.stdout'
  changed_when:
    - '"Nothing to do" not in result.stdout'
  notify: Reboot the system

- block:
    - name: Create the systemd overrides directory for Docker.
      file:
        name: "/etc/systemd/system/docker.service.d"
        state: directory

    - name: Override the systemd unit for Docker.
      template:
        src: docker-override.conf.j2
        dest: "/etc/systemd/system/docker.service.d/override.conf"
      register: _docker_systemd_override

    - name: Apply reboot immediately to enable latest update snapshot
      ansible.builtin.meta: flush_handlers

    - name: Reload systemd and restart Docker.
      service:
        name: docker
        state: "{% if docker_service_state != 'stopped' %}restarted{% else %}stopped{% endif %}"
        daemon_reload: yes
      when: _docker_systemd_override.changed

  when: docker_service_override | length > 0
    and ansible_service_mgr == 'systemd'

- name: Make sure the Docker daemon configuration directory exists.
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Configure the Docker daemon.
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: restart docker
  tags:
    - docker_daemon_config

- name: Apply reboot immediately to enable latest update snapshot
  ansible.builtin.meta: flush_handlers

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300

- name: Enable the Docker daemon service and start it.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
